#!/usr/bin/env python3
"""
ZoneStrike — Network Recon & Port Scanner
DIO Cybersecurity Bootcamp — AppSec/DevSecOps
"""

import socket
import argparse
import sys
import json
import concurrent.futures
from datetime import datetime

VERSION = "1.0.0"

COMMON_PORTS = {
    21: "FTP", 22: "SSH", 23: "Telnet", 25: "SMTP",
    53: "DNS", 80: "HTTP", 110: "POP3", 143: "IMAP",
    443: "HTTPS", 445: "SMB", 3306: "MySQL", 3389: "RDP",
    5432: "PostgreSQL", 6379: "Redis", 8080: "HTTP-Alt",
    8443: "HTTPS-Alt", 27017: "MongoDB"
}

def resolve_host(target: str) -> str:
    try:
        return socket.gethostbyname(target)
    except socket.gaierror:
        print(f"[ERROR] Could not resolve host: {target}")
        sys.exit(1)

def scan_port(target: str, port: int, timeout: float = 1.0) -> dict:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(timeout)
            result = s.connect_ex((target, port))
            if result == 0:
                service = COMMON_PORTS.get(port, "Unknown")
                banner = ""
                try:
                    s.send(b"HEAD / HTTP/1.0\r\n\r\n")
                    banner = s.recv(256).decode(errors="ignore").split("\n")[0].strip()
                except Exception:
                    pass
                return {"port": port, "state": "open", "service": service, "banner": banner}
    except Exception:
        pass
    return {"port": port, "state": "closed", "service": "", "banner": ""}

def scan_target(target: str, ports: list, threads: int = 100, timeout: float = 1.0) -> list:
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=threads) as executor:
        futures = {executor.submit(scan_port, target, port, timeout): port for port in ports}
        for future in concurrent.futures.as_completed(futures):
            result = future.result()
            if result["state"] == "open":
                results.append(result)
    return sorted(results, key=lambda x: x["port"])

def generate_html_report(target: str, ip: str, open_ports: list, scan_time: str) -> str:
    rows = ""
    for p in open_ports:
        severity = "HIGH" if p["port"] in [21, 23, 3389] else "MEDIUM" if p["port"] in [80, 8080] else "INFO"
        color = "#ff4d5a" if severity == "HIGH" else "#ff8a1f" if severity == "MEDIUM" else "#29d3ff"
        rows += f"""
        <tr>
            <td>{p['port']}</td>
            <td style="color:#35e0a1">OPEN</td>
            <td>{p['service']}</td>
            <td style="color:{color}">{severity}</td>
            <td>{p['banner'][:60] if p['banner'] else '-'}</td>
        </tr>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ZoneStrike Report — {target}</title>
<style>
  body {{ font-family: monospace; background: #0b1220; color: #c8d8f0; margin: 0; padding: 24px; }}
  h1 {{ color: #22d3ee; }} h2 {{ color: #94a3b8; font-size: 14px; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 24px; }}
  th {{ background: #112038; color: #22d3ee; padding: 10px; text-align: left; border-bottom: 1px solid #22314a; }}
  td {{ padding: 8px 10px; border-bottom: 1px solid #1a2840; }}
  tr:hover {{ background: #112038; }}
  .badge {{ background: #22d3ee20; border: 1px solid #22d3ee50; padding: 2px 8px; border-radius: 4px; }}
</style>
</head>
<body>
<h1>⚡ ZoneStrike — Scan Report</h1>
<h2>Target: {target} ({ip}) | Scan: {scan_time} | Open ports: {len(open_ports)}</h2>
<table>
  <thead><tr><th>Port</th><th>State</th><th>Service</th><th>Severity</th><th>Banner</th></tr></thead>
  <tbody>{rows if rows else '<tr><td colspan="5" style="text-align:center;color:#666">No open ports found</td></tr>'}</tbody>
</table>
<p style="color:#4a6080;margin-top:32px;font-size:12px">Generated by ZoneStrike v{VERSION} — Educational use only</p>
</body>
</html>"""

def main():
    parser = argparse.ArgumentParser(
        description="ZoneStrike — Network Recon & Port Scanner",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n  python zonestrike.py 192.168.1.1\n  python zonestrike.py scanme.nmap.org --ports 1-1000\n  python zonestrike.py 10.0.0.1 --output report.html"
    )
    parser.add_argument("target", help="Target IP or hostname")
    parser.add_argument("--ports", default="common", help="Port range: 'common', '1-1024', '80,443,8080'")
    parser.add_argument("--threads", type=int, default=100, help="Number of threads (default: 100)")
    parser.add_argument("--timeout", type=float, default=1.0, help="Connection timeout in seconds (default: 1.0)")
    parser.add_argument("--output", help="Save HTML report to file")
    parser.add_argument("--json", action="store_true", help="Output results as JSON")
    parser.add_argument("--version", action="version", version=f"ZoneStrike v{VERSION}")
    args = parser.parse_args()

    print(f"\n  ⚡ ZoneStrike v{VERSION} — Network Recon Tool")
    print(f"  Target: {args.target}")

    ip = resolve_host(args.target)
    print(f"  Resolved: {ip}")

    if args.ports == "common":
        ports = list(COMMON_PORTS.keys())
    elif "-" in args.ports:
        start, end = map(int, args.ports.split("-"))
        ports = list(range(start, end + 1))
    else:
        ports = [int(p) for p in args.ports.split(",")]

    print(f"  Scanning {len(ports)} ports with {args.threads} threads...\n")
    start_time = datetime.now()
    open_ports = scan_target(ip, ports, args.threads, args.timeout)
    duration = (datetime.now() - start_time).total_seconds()
    scan_time = start_time.strftime("%Y-%m-%d %H:%M:%S")

    if args.json:
        print(json.dumps({"target": args.target, "ip": ip, "open_ports": open_ports}, indent=2))
        return

    print(f"  {'PORT':<8} {'STATE':<10} {'SERVICE':<15} {'BANNER'}")
    print(f"  {'-'*60}")
    for p in open_ports:
        print(f"  {p['port']:<8} {'OPEN':<10} {p['service']:<15} {p['banner'][:40] if p['banner'] else ''}")

    print(f"\n  Scan completed in {duration:.2f}s — {len(open_ports)} open port(s) found\n")

    if args.output:
        html = generate_html_report(args.target, ip, open_ports, scan_time)
        with open(args.output, "w") as f:
            f.write(html)
        print(f"  Report saved: {args.output}\n")

if __name__ == "__main__":
    main()
